const strings = {
    signUp: {
      account: 'Have an account?',
      logIn: 'Login',
      hi: 'Hi!',
      createAccount: 'Create a New Account',
      email: 'Email',  
      password: 'Password',
      reEnterPassword: 'Re-enter Password',
      signUp: 'Sign Up',
      whySignUp: 'Why Sign Up?',
      connect: 'Get Connected with 1,000s of Merchants',
      works: 'How it works?',
      emptyPassword: 'Password can not be empty',
      invalidCnfPassword: 'Confirm password doesn\'t match password',
      emptyCnfPassword: 'Confirm password can not be empty',
      emptyEmail: "Ëmail can not be empty",
      invalidEmail: "Invalid email formate",
      emailPlaceholder: 'abc.rentry@xyzpteltd.com.sg',
      passwordPlaceholder: '**********'
    },
    logIn: {
        welcomeBack: 'Welcome Back!',
        email: 'Email',  
        password: 'Password',
        forgetPassword: 'Forget Password ?',
        noAccount: 'No account?',
        signUpHere: 'Sign Up Here',
        logIn: 'Log In',
        needHelp: 'Need Help?',
        emailPlaceholder: 'abc.rentry@xyzpteltd.com.sg',
        passwordPlaceholder: '**********'
    },
    work:{
        howItWorks: 'How it works?',
        getStarted: '3 Simple Steps to Get Started!',
        signUp: 'Sign Up',
        learnMore: 'Learn More',
        para: 'Whether you are buying or selling,renting or \n  leasing ,you can manage all your activities. \n \t \t \t \t \t \t CONVENIENTLY & EFFECTIVELY',
        findService: 'Buy/Find Services',
        finishOff: 'Finish Off',
        one: '1',
        two: '2',
        three: '3'
    },
    forgetPass: {
      forget: 'Forget Password?',
      enterEmail: '  Enter Your Registered E-Mail & We’ll send you the link to the reset password',
      email: 'Email',
      emailPlaceholder: 'abc.rentry@xyzpteltd.com.sg',
      signUpHere: 'Sign Up Here',
      noAccount: 'No account?',
      needHelp: 'Need Help?',
      submit: 'Submit'
    },
    resetPass:{
      reset: 'Reset Password',
      email: 'Email',  
      password: 'Password',
      reEnterPassword: 'Re-enter Password',    
      emptyPassword: 'Password can not be empty',
      invalidCnfPassword: 'Confirm password doesn\'t match password',
      emptyCnfPassword: 'Confirm password can not be empty',
      emptyEmail: "Ëmail can not be empty",
      invalidEmail: "Invalid email formate",
      emailPlaceholder: 'abc.rentry@xyzpteltd.com.sg',
      passwordPlaceholder: '**********',
      submit: 'Submit',
      cancel: 'Cancel',
      needHelp: 'Need Help?',
    },
    success:{
      success: 'SUCCESS!',
      welcomeBack: 'Welcome Back!',
      email: 'abc.rentry@xyzpteltd.com.sg',
      continue: 'Press continue to gain access to your account!',
      continue: 'Continue',
      needHelp: 'Need Help?',
    },
    verification: {
      verification: 'Verification',
      hurry: 'Hurray!',
      mailSent: 'We have sent an email to',
      email: 'abc.rentry@xyzpteltd.com.sg',
      clickMail:'Just click on the link in the emailto continue with the signup.',
      findMail: 'Still can’t find the Email?',
      resendMail: 'Resend Email'
    },
    uen:{
      step: 'One more step',
      bitMore: 'A bit more!',
      signUp: 'Sign Up',
      profileSetup: 'Profile Setup',
      getStarted: 'Get Started',
      access: 'For Full Access Please Use:',
      uen: 'UEN*',
      companyName: 'Company Name*',
      content: '2 users have been registered to this UEN. Maximum of 3 users can be registered to any particular UEN for free',
      check1: 'Are you Authorised to Participate on this platform for the said concern?',
      check2: 'I Agree with Terms & Conditions',
      submit: 'Submit',
      freeLancer: 'Freelancers?',
      click: 'Click Here',
      emailPlaceholder: " ",
      xyz: "XYZ Pte Ltd",
    },
  };
  
  export default strings;
  
  